version: '3.1'

services:
  # postgres:
  #   image: postgres
  #   environment:
  #     - POSTGRES_HOST=${POSTGRES_HOST}
  #     - POSTGRES_PORT=${POSTGRES_PORT}
  #     - POSTGRES_USER=${POSTGRES_USER}  
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #   ports:
  #     - 80:5432
  #   volumes:
  #     - ./docker/postgres:/var/lib/postgresql/data
  #   labels:
  #     - kompose.service.type=loadbalancer

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: privatepassword
    ports:
      - 8081:80
    labels:
      - kompose.service.type=loadbalancer
  hello-world:
    image: nginx
    ports:
      - 8080:80
    labels:
      - kompose.service.type=loadbalancer