version: '3.1'
services:

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: tutorial
      POSTGRES_DB: iam
      POSTGRES_PASSWORD: privatepassword
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    deploy:
      replicas: 1
    volumes:
      - ./prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=365d'
    ports:
      - '9090:9090'
    labels:
      - kompose.service.type=loadbalancer
  
  alertmanager:
    image: prom/alertmanager:v0.18.0
    container_name: alertmanager
    deploy:
      replicas: 1
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - '9093:9093'
    labels:
      - kompose.service.type=loadbalancer

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   environment:
  #     - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
  #   deploy:
  #     replicas: 1
  #   depends_on:
  #     - prometheus
  #   volumes:
  #     - grafana-data:/var/lib/grafana
  #     - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
  #     - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
  #     - ./grafana/grafana.ini:/etc/grafana/grafana.ini
  #     - ./grafana/dashboards:/var/lib/grafana/dashboards
  #   ports:
  #     - '3000:3000'
  #   labels:
  #     - kompose.service.type=loadbalancer

  # blackbox:
  #   image: prom/blackbox-exporter:v0.14.0
  #   container_name: blackbox_exporter
  #   deploy:
  #     replicas: 1
  #   volumes:
  #     - ./blackbox:/config
  #   ports:
  #     - '9115:9115'
  #   labels:
  #     - kompose.service.type=loadbalancer

  # node_exporter:
  #   image: prom/node-exporter:v0.18.1
  #   container_name: node_exporter
  #   deploy:
  #     replicas: 1
  #   network_mode: 'bridge'
  #   ports:
  #     - '9100:9100'
  #   labels:
  #     - kompose.service.type=loadbalancer

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/iam?sslmode=disable
    links:
        - postgres
        - prometheus
    labels:
      - kompose.service.type=loadbalancer

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: privatepassword
  #   ports:
  #     - 8081:80
  #   labels:
  #     - kompose.service.type=loadbalancer
      
# volumes:
#   prometheus-data:
#     driver: local
#   grafana-data:
#     driver: local
