version: '3.1'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres  
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=iam
    network_mode: bridge
    ports:
      - 127.0.0.1:5432:5432
    
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
      # - ./:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: privatepassword
      PGADMIN_LISTEN_PORT: 8000
    network_mode: bridge
    ports:
      - 127.0.0.1:8000:8000


  fastify:
    network_mode: bridge
    image: fastify:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:3000:3000
      
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres  
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=iam
      - POSTGRES_TEST_PORT=5433
    depends_on:
      - postgres